### ISSUE TITLE
NES and SNES Classic Mini Controller dpad buttons

### ISSUE THREAD

**Issue by areaperson** [mooware/arduino-wii-usb#1]
Thanks for this script! I have it on a Leonardo and am using it with Windows 10, and wasn't sure what to expect when the NES and SNES dpad buttons only registered on the "Point of View Hat" and not the X Axis / Y Axis

I guess the Windows 10 gamepad API only looks to the axes for movement and the script doesn't set them from dpad+joystick? I'm only using this adapter with nes/snes classic controllers and don't expect to use it with a controller that has a joystick, so the following worked for my case :)

Replace this
```ino
Gamepad.xAxis((int16_t(data.left_stick_x) - 32) << 10);
Gamepad.yAxis((int16_t(data.left_stick_y) - 32) << 10);
```

With this
```ino
if (data.button_up == 0)            Gamepad.yAxis(-32768);
if (data.button_right == 0)         Gamepad.xAxis(32767);
if (data.button_down == 0)          Gamepad.yAxis(32767);
if (data.button_left == 0)          Gamepad.xAxis(-32768);
```

**Comment by mooware** [comment]
Some controllers have D-Pad plus analog sticks (https://en.wikipedia.org/wiki/Classic_Controller), so I'd have to recognize the different controller types in order to do this.

I'm not sure what you mean by "Windows 10 gamepad API". Do you have issues with a specific application or game? I'd expect that e.g. the standard XBox 360 and XBox One controllers would also report their D-Pad the same way. Or are you specifically expecting the D-Pad to act as an analog stick?

**Comment by areaperson** [comment]
Snes9X didn't recognize the dpad but it had when I tested the same first-party controllers with a commercial adapter. However it looks like the problem is with Snes9X. I just switched back to the dpad code and the buttons are recognized in Steam and RetroArch. Why didn't I check other software first!?..

So I don't think there is an issue with Windows 10 and dpad :) I guess there is some difference between the dpad/HAT code here and the code in these cheap commercial adapters (unbranded, bundled with a third-party controller) that Snes9X isn't sure about.

Thanks for the help and code!
